-- Create questions table
CREATE TABLE IF NOT EXISTS public.questions (
    id SERIAL PRIMARY KEY,
    set_id INTEGER NOT NULL,
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    correct_index INTEGER NOT NULL
);

-- Original 20 questions (sets 1-4)
INSERT INTO public.questions (set_id, question, options, correct_index) VALUES
(1, 'What is the chemical symbol for water?', '["H2O", "CO2", "O2", "NaCl"]'::jsonb, 0),
(1, 'How many bones are in the human body?', '["206", "208", "210", "212"]'::jsonb, 0),
(1, 'What planet is known as the "Red Planet"?', '["Venus", "Mars", "Jupiter", "Saturn"]'::jsonb, 1),
(1, 'What is the powerhouse of the cell?', '["Nucleus", "Mitochondria", "Ribosome", "Golgi"]'::jsonb, 1),
(1, 'Which gas do plants absorb from the air?', '["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"]'::jsonb, 1),
(2, 'In which year did World War II end?', '["1944", "1945", "1946", "1947"]'::jsonb, 1),
(2, 'Who was the first President of the United States?', '["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"]'::jsonb, 2),
(2, 'Which ancient wonder was located in Alexandria?', '["Hanging Gardens", "Lighthouse", "Colossus", "Pyramids"]'::jsonb, 1),
(2, 'Who painted the Sistine Chapel ceiling?', '["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"]'::jsonb, 1),
(2, 'In which year did the Titanic sink?', '["1910", "1912", "1914", "1916"]'::jsonb, 1),
(3, 'What is the longest river in the world?', '["Amazon", "Nile", "Yangtze", "Mississippi"]'::jsonb, 1),
(3, 'Which country has the most natural lakes?', '["Canada", "Russia", "Finland", "Sweden"]'::jsonb, 0),
(3, 'What is the capital of Australia?', '["Sydney", "Melbourne", "Canberra", "Perth"]'::jsonb, 2),
(3, 'Which is the smallest continent?', '["Europe", "Australia", "Africa", "Asia"]'::jsonb, 1),
(3, 'What is the highest mountain in the world?', '["K2", "Kangchenjunga", "Everest", "Lhotse"]'::jsonb, 2),
(4, 'How many players are on a basketball team?', '["5", "6", "7", "8"]'::jsonb, 0),
(4, 'Who directed the movie "Inception"?', '["Steven Spielberg", "Christopher Nolan", "Martin Scorsese", "Quentin Tarantino"]'::jsonb, 1),
(4, 'In which sport is the term "home run" used?', '["Baseball", "Cricket", "Soccer", "Tennis"]'::jsonb, 0),
(4, 'What is the highest-grossing film of all time?', '["Titanic", "Avatar", "Avengers: Endgame", "Star Wars"]'::jsonb, 1),
(4, 'How many rings are on the Olympic symbol?', '["4", "5", "6", "7"]'::jsonb, 1);

-- Additional 70 questions (sets 5-18)
INSERT INTO public.questions (set_id, question, options, correct_index) VALUES
(5, 'What is the speed of light?', '["300000 km/s", "150000 km/s", "450000 km/s", "600000 km/s"]'::jsonb, 0),
(5, 'What is the atomic number of carbon?', '["6", "8", "12", "14"]'::jsonb, 0),
(5, 'Which scientist developed the theory of relativity?', '["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking"]'::jsonb, 1),
(5, 'What is the pH of pure water?', '["7", "5", "9", "0"]'::jsonb, 0),
(5, 'What is the largest organ in the human body?', '["Liver", "Skin", "Heart", "Brain"]'::jsonb, 1),
(6, 'What does DNA stand for?', '["Deoxyribonucleic acid", "Deoxyribose nucleic acid", "Dioxyribonucleic acid", "Deoxyribonucleic acid"]'::jsonb, 0),
(6, 'Which planet has the most moons?', '["Jupiter", "Saturn", "Uranus", "Neptune"]'::jsonb, 1),
(6, 'What is the chemical formula for salt?', '["NaCl", "KCl", "CaCl", "MgCl"]'::jsonb, 0),
(6, 'Who discovered penicillin?', '["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Jonas Salk"]'::jsonb, 0),
(6, 'What is the boiling point of water in Celsius?', '["100", "0", "50", "212"]'::jsonb, 0),
(7, 'Who was the first emperor of Rome?', '["Julius Caesar", "Augustus", "Nero", "Caligula"]'::jsonb, 1),
(7, 'In which year did the American Revolution begin?', '["1775", "1776", "1783", "1492"]'::jsonb, 0),
(7, 'Who built the Taj Mahal?', '["Shah Jahan", "Akbar", "Babur", "Aurangzeb"]'::jsonb, 0),
(7, 'What was the name of the ship that carried the Pilgrims to America?', '["Mayflower", "Santa Maria", "Nina", "Pinta"]'::jsonb, 0),
(7, 'Who was the first woman to fly solo across the Atlantic?', '["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"]'::jsonb, 0),
(8, 'What year did the Berlin Wall fall?', '["1989", "1991", "1985", "1990"]'::jsonb, 0),
(8, 'Who was the leader of the Bolshevik Revolution?', '["Vladimir Lenin", "Joseph Stalin", "Leon Trotsky", "Karl Marx"]'::jsonb, 0),
(8, 'In which year was the Magna Carta signed?', '["1215", "1066", "1348", "1492"]'::jsonb, 0),
(8, 'Who was the first pharaoh of Egypt?', '["Narmer", "Tutankhamun", "Ramses II", "Cleopatra"]'::jsonb, 0),
(8, 'What was the main cause of the French Revolution?', '["Taxation without representation", "Monarchy abuse", "Religious conflict", "Foreign invasion"]'::jsonb, 1),
(9, 'What is the largest desert in the world?', '["Sahara", "Gobi", "Antarctic", "Arabian"]'::jsonb, 2),
(9, 'Which country is known as the Land of the Rising Sun?', '["China", "Japan", "Korea", "Thailand"]'::jsonb, 1),
(9, 'What is the capital of Canada?', '["Toronto", "Vancouver", "Ottawa", "Montreal"]'::jsonb, 2),
(9, 'Which ocean is the deepest?', '["Atlantic", "Indian", "Arctic", "Pacific"]'::jsonb, 3),
(9, 'What is the longest mountain range in the world?', '["Himalayas", "Andes", "Rockies", "Alps"]'::jsonb, 1),
(10, 'Which continent is home to the Amazon Rainforest?', '["Africa", "South America", "Asia", "Australia"]'::jsonb, 1),
(10, 'What is the smallest country in the world?', '["Monaco", "Vatican City", "San Marino", "Liechtenstein"]'::jsonb, 1),
(10, 'Which river flows through Paris?', '["Thames", "Seine", "Danube", "Rhine"]'::jsonb, 1),
(10, 'What is the largest lake in Africa?', '["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"]'::jsonb, 0),
(10, 'Which country has the most volcanoes?', '["Indonesia", "Japan", "Iceland", "Italy"]'::jsonb, 0),
(11, 'In which sport is the term "slam dunk" used?', '["Basketball", "Volleyball", "Tennis", "Badminton"]'::jsonb, 0),
(11, 'How many players are on a soccer team?', '["11", "9", "7", "5"]'::jsonb, 0),
(11, 'Who won the most Olympic gold medals?', '["Michael Phelps", "Usain Bolt", "Carl Lewis", "Jesse Owens"]'::jsonb, 0),
(11, 'What is the distance of a marathon?', '["42.195 km", "50 km", "30 km", "21.1 km"]'::jsonb, 0),
(11, 'In which sport do you perform a "birdie"?', '["Golf", "Badminton", "Tennis", "Cricket"]'::jsonb, 1),
(12, 'Who is known as the "King of Football"?', '["Lionel Messi", "Cristiano Ronaldo", "Pelé", "Maradona"]'::jsonb, 2),
(12, 'What is the main equipment in tennis?', '["Bat", "Racket", "Stick", "Club"]'::jsonb, 1),
(12, 'How many holes are on a standard golf course?', '["9", "18", "12", "15"]'::jsonb, 1),
(12, 'In which year was the first modern Olympics held?', '["1896", "1900", "1880", "1920"]'::jsonb, 0),
(12, 'Who holds the record for the most home runs in MLB?', '["Babe Ruth", "Hank Aaron", "Barry Bonds", "Albert Pujols"]'::jsonb, 2),
(13, 'Who played the role of Harry Potter?', '["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Tom Felton"]'::jsonb, 0),
(13, 'What is the name of the fictional wizarding school in Harry Potter?', '["Hogwarts", "Durmstrang", "Beauxbatons", "Ilvermorny"]'::jsonb, 0),
(13, 'Which movie won the first Oscar?', '["Wings", "The Jazz Singer", "Sunrise", "7th Heaven"]'::jsonb, 0),
(13, 'Who is the lead singer of the Beatles?', '["John Lennon", "Paul McCartney", "George Harrison", "Ringo Starr"]'::jsonb, 0),
(13, 'What year did Star Wars Episode IV release?', '["1977", "1980", "1975", "1983"]'::jsonb, 0),
(14, 'Who directed Jurassic Park?', '["Steven Spielberg", "George Lucas", "James Cameron", "Christopher Nolan"]'::jsonb, 0),
(14, 'What is the highest-grossing animated film?', '["The Lion King", "Finding Nemo", "Frozen II", "Toy Story 3"]'::jsonb, 2),
(14, 'Who won the first Academy Award for Best Actor?', '["Emil Jannings", "Warner Baxter", "George Arliss", "Lionel Barrymore"]'::jsonb, 0),
(14, 'What band is known for the song "Bohemian Rhapsody"?', '["The Beatles", "Queen", "Led Zeppelin", "The Rolling Stones"]'::jsonb, 1),
(14, 'In which year was the first Superman comic published?', '["1938", "1940", "1935", "1945"]'::jsonb, 0),
(15, 'What is the only mammal that can fly?', '["Flying squirrel", "Bat", "Pterodactyl", "Sugar glider"]'::jsonb, 1),
(15, 'How many hearts does an octopus have?', '["1", "2", "3", "4"]'::jsonb, 2),
(15, 'What is the rarest blood type?', '["O-", "AB+", "B-", "A+"]'::jsonb, 1),
(15, 'Which animal can hold its breath the longest?', '["Human", "Elephant", "Sperm whale", "Sea lion"]'::jsonb, 2),
(15, 'What is the smallest bone in the human body?', '["Femur", "Stapes", "Humerus", "Tibia"]'::jsonb, 1),
(16, 'How many taste buds does the average human have?', '["1000", "5000", "10000", "2000"]'::jsonb, 1),
(16, 'What is the only letter that doesnt appear on the periodic table?', '["J", "Q", "X", "Z"]'::jsonb, 0),
(16, 'Which fruit is known as the "king of fruits" in Southeast Asia?', '["Mango", "Durian", "Pineapple", "Banana"]'::jsonb, 1),
(16, 'What is the only food that doesnt spoil?', '["Rice", "Honey", "Salt", "Sugar"]'::jsonb, 1),
(16, 'How many colors are in a rainbow?', '["5", "6", "7", "8"]'::jsonb, 2),
(17, 'What has keys but cant open locks?', '["Piano", "Computer", "Car", "House"]'::jsonb, 0),
(17, 'What gets wetter as it dries?', '["Towel", "Hair", "Clothes", "Sponge"]'::jsonb, 0),
(17, 'What has a head, a tail, but no body?', '["Snake", "Coin", "Comet", "Arrow"]'::jsonb, 1),
(17, 'What can you catch but not throw?', '["Ball", "Cold", "Fish", "Bird"]'::jsonb, 1),
(17, 'What has one eye but cant see?', '["Cyclops", "Needle", "Camera", "Storm"]'::jsonb, 1),
(18, 'I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?', '["Echo", "Ghost", "Wind", "Shadow"]'::jsonb, 0),
(18, 'The more you take, the more you leave behind. What am I?', '["Footsteps", "Memories", "Time", "Money"]'::jsonb, 0),
(18, 'I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?', '["Map", "Globe", "Atlas", "Planet"]'::jsonb, 0),
(18, 'What can travel around the world while staying in a corner?', '["Stamp", "Coin", "Key", "Ring"]'::jsonb, 0),
(18, 'What has a neck but no head?', '["Bottle", "Shirt", "Guitar", "River"]'::jsonb, 0),
(19, 'What is 2 + 2?', '["3", "4", "5", "6"]'::jsonb, 1),
(19, 'What is the square root of 16?', '["2", "4", "8", "16"]'::jsonb, 1),
(19, 'What is the value of pi (approximately)?', '["3.14", "2.71", "1.41", "9.81"]'::jsonb, 0),
(19, 'How many sides does a hexagon have?', '["5", "6", "7", "8"]'::jsonb, 1),
(19, 'What is 10% of 100?', '["10", "20", "5", "1"]'::jsonb, 0),
(20, 'Who wrote "Romeo and Juliet"?', '["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"]'::jsonb, 1),
(20, 'What is the name of the wizard in "The Lord of the Rings"?', '["Gandalf", "Saruman", "Radagast", "Dumbledore"]'::jsonb, 0),
(20, 'In "To Kill a Mockingbird", who is the main character?', '["Scout Finch", "Atticus Finch", "Boo Radley", "Tom Robinson"]'::jsonb, 0),
(20, 'Who wrote "1984"?', '["George Orwell", "Aldous Huxley", "Ray Bradbury", "Philip K. Dick"]'::jsonb, 0),
(20, 'What is the famous line from "Hamlet"?', '["To be or not to be", "All the world is a stage", "Et tu, Brute", "Friends, Romans, countrymen"]'::jsonb, 0);

-- Enable RLS for public read access
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON public.questions FOR SELECT USING (true);
